In [4]:
import os
os.getcwd()

'C:\\Users\\JASWANTH\\Desktop\\Remote internship 2020\\python codes'

In [5]:
os.chdir("C:\\Users\\JASWANTH\\Desktop\\Remote internship 2020\\datasets")

In [6]:
os.getcwd()

'C:\\Users\\JASWANTH\\Desktop\\Remote internship 2020\\datasets'

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [8]:
data1=pd.read_csv('kidney_disease.csv')
data1

id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present   
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent   
..   ...   ...   ...    ...  ...  ...     ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no   
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no   
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes   
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes   
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no   
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no   
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no   
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no   
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no   
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[400 rows x 26 columns]

In [9]:
data1.shape

(400, 26)

In [10]:
#Since Id is Not Required it is Dropped from the data
data1=data1.drop(['id'],axis=1)
data1.head()

age    bp     sg   al   su     rbc        pc         pcc          ba  \
0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

     bgr  ...  pcv    wc   rc  htn   dm cad appet   pe  ane classification  
0  121.0  ...   44  7800  5.2  yes  yes  no  good   no   no            ckd  
1    NaN  ...   38  6000  NaN   no   no  no  good   no   no            ckd  
2  423.0  ...   31  7500  NaN   no  yes  no  poor   no  yes            ckd  
3  117.0  ...   32  6700  3.9  yes   no  no  poor  yes  yes            ckd  
4  106.0  ...   35  7300  4.6   no   no  no  good   no   no            ckd  

[5 rows x 25 columns]

# Check for null values

In [11]:
data1.isnull().any()

age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [12]:
data1.apply(lambda x:sum(x.isnull()),axis=0)

age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

# Filling the null values in the data

In [13]:
#The Categorical Values in the Dataset are converted into Numerical Values For Better Representation of the Data

data1['rbc'].fillna('normal',inplace = True)
data1['rbc'].replace(['normal','abnormal'],[0,1],inplace = True)

data1['pc'].fillna('normal',inplace = True)
data1['pc'].replace(['normal','abnormal'],[0,1],inplace = True)

data1['pcc'].fillna('notpresent',inplace = True)
data1['pcc'].replace(['notpresent','present'],[0,1],inplace = True)

data1['ba'].fillna('notpresent',inplace = True)
data1['ba'].replace(['notpresent','present'],[0,1],inplace = True)

data1['htn'].fillna('no',inplace = True)
data1['htn'].replace(['no','yes'],[0,1],inplace = True)

data1['dm'].fillna('no',inplace = True)
#Replacing '\tno','\tyes',' yes' with 'no','yes','yes'
data1['dm'].replace(['\tno','\tyes',' yes'],['no','yes','yes'],inplace = True)
data1['dm'].replace(['no','yes'],[0,1],inplace = True)

data1['appet'].fillna('good',inplace = True)
data1['appet'].replace(['good','poor'],[0,1],inplace = True)

data1['pe'].fillna('no',inplace = True)
data1['pe'].replace(['no','yes'],[0,1],inplace = True)

data1['ane'].fillna('no',inplace = True)
data1['ane'].replace(['no','yes'],[0,1],inplace = True)

In [14]:
data1.head()

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...  pcv    wc   rc  \
0  48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...   44  7800  5.2   
1   7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...   38  6000  NaN   
2  62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...   31  7500  NaN   
3  48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...   32  6700  3.9   
4  51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...   35  7300  4.6   

   htn  dm cad appet pe  ane  classification  
0    1   1  no     0  0    0             ckd  
1    0   0  no     0  0    0             ckd  
2    0   1  no     1  0    1             ckd  
3    1   0  no     1  1    1             ckd  
4    0   0  no     0  0    0             ckd  

[5 rows x 25 columns]

In [15]:
data1['rbc'].value_counts()
data1['pc'].value_counts()
data1['pcc'].value_counts()
data1['ba'].value_counts()
data1['htn'].value_counts()
data1['dm'].value_counts()
data1['appet'].value_counts()
data1['pe'].value_counts()
data1['ane'].value_counts()

0    340
1     60
Name: ane, dtype: int64

In [16]:
data1['pcv'].replace(['\t?','\t43'],[52,43],inplace = True)
data1['pcv'].fillna(52,inplace = True)

In [17]:
data1['pcv'].value_counts()

52    71
41    21
52    21
48    19
44    19
40    16
43    14
42    13
45    13
28    12
32    12
36    12
33    12
50    12
37    11
34    11
46     9
30     9
35     9
29     9
31     8
39     7
24     7
26     6
38     5
47     4
51     4
54     4
49     4
53     4
22     3
25     3
27     3
19     2
23     2
9      1
18     1
21     1
43     1
17     1
20     1
14     1
16     1
15     1
Name: pcv, dtype: int64

In [18]:
data1['wc'].replace(['\t8400','\t6200','\t?'],[8400,6200,9800],inplace = True)
data1['wc'].fillna(9800,inplace = True)

In [19]:
data1['wc'].value_counts()

9800     106
9800      11
6700      10
9200       9
9600       9
        ... 
5100       1
16700      1
11800      1
10800      1
2600       1
Name: wc, Length: 92, dtype: int64

In [20]:
data1['rc'].replace(['\t?'],[5.2],inplace = True)
data1['rc'].fillna(5.2,inplace = True)

In [21]:
data1['rc'].value_counts()

5.2    131
5.2     18
4.5     16
4.9     14
4.7     11
4.8     10
3.9     10
3.4      9
4.6      9
5.0      8
5.5      8
5.9      8
3.7      8
6.1      8
3.8      7
5.8      7
5.4      7
5.3      7
4.2      6
4.3      6
5.6      6
6.2      5
6.4      5
5.7      5
3.2      5
4.4      5
5.1      5
6.5      5
4.1      5
6.0      4
6.3      4
3.6      4
4.0      3
3.5      3
3.3      3
4        3
2.1      2
3.0      2
2.8      2
2.5      2
2.7      2
2.9      2
3.1      2
2.6      2
5        2
3        1
2.4      1
2.3      1
8.0      1
Name: rc, dtype: int64

In [22]:
data1.isnull().any()

age                True
bp                 True
sg                 True
al                 True
su                 True
rbc               False
pc                False
pcc               False
ba                False
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv               False
wc                False
rc                False
htn               False
dm                False
cad                True
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [23]:
data1.apply(lambda x:sum(x.isnull()),axis=0)

age                9
bp                12
sg                47
al                46
su                49
rbc                0
pc                 0
pcc                0
ba                 0
bgr               44
bu                19
sc                17
sod               87
pot               88
hemo              52
pcv                0
wc                 0
rc                 0
htn                0
dm                 0
cad                2
appet              0
pe                 0
ane                0
classification     0
dtype: int64

In [24]:
data1['cad'].replace(['\tno'],['no'],inplace = True)
data1['cad'].value_counts()

no     364
yes     34
Name: cad, dtype: int64

In [25]:
data1['cad'].fillna('no',inplace = True)
data1['cad'].replace(['no','yes'],[0,1],inplace = True)
data1['cad'].value_counts()

0    366
1     34
Name: cad, dtype: int64

In [26]:
data1['classification'].replace(['ckd\t'],['ckd'],inplace=True)

data1['classification'].value_counts()

ckd       250
notckd    150
Name: classification, dtype: int64

In [27]:
data1['classification'].fillna('ckd',inplace = True)
data1['classification'].replace(['ckd','notckd'],[0,1],inplace = True)
data1['classification'].value_counts()

0    250
1    150
Name: classification, dtype: int64

In [28]:
data1['rc']=data1['rc'].astype('float')

data1['pcv'] =data1['pcv'].astype('float')

data1['wc'] =data1['wc'].astype('float')

In [29]:
data1['rbc'].fillna('normal',inplace=True)
data1['pc'].fillna('normal',inplace=True)
data1['pcc'].fillna('notpresent',inplace=True)
data1['ba'].fillna('notpresent',inplace=True)
data1['htn'].fillna('no',inplace=True)
data1['dm'].fillna('no',inplace=True)
data1['cad'].fillna('no',inplace=True)
data1['appet'].fillna('good',inplace=True)
data1['pe'].fillna('no',inplace=True)
data1['ane'].fillna('no',inplace=True)

In [30]:
data1.dtypes

age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                 int64
pc                  int64
pcc                 int64
ba                  int64
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv               float64
wc                float64
rc                float64
htn                 int64
dm                  int64
cad                 int64
appet               int64
pe                  int64
ane                 int64
classification      int64
dtype: object

In [31]:
data1.isnull().any()

age                True
bp                 True
sg                 True
al                 True
su                 True
rbc               False
pc                False
pcc               False
ba                False
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [32]:
features = data1.iloc[:,:].values
features

array([[48.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [ 7.   , 50.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [62.   , 80.   ,  1.01 , ...,  0.   ,  1.   ,  0.   ],
       ...,
       [12.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  1.   ],
       [17.   , 60.   ,  1.025, ...,  0.   ,  0.   ,  1.   ],
       [58.   , 80.   ,  1.025, ...,  0.   ,  0.   ,  1.   ]])

In [33]:
data1.head()

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0  48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...  44.0  7800.0   
1   7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...  38.0  6000.0   
2  62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...  31.0  7500.0   
3  48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...  32.0  6700.0   
4  51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...  35.0  7300.0   

    rc  htn  dm  cad  appet  pe  ane  classification  
0  5.2    1   1    0      0   0    0               0  
1  5.2    0   0    0      0   0    0               0  
2  5.2    0   1    0      1   0    1               0  
3  3.9    1   0    0      1   1    1               0  
4  4.6    0   0    0      0   0    0               0  

[5 rows x 25 columns]

In [34]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data1['pc']=l.fit_transform(data1['pc'])
data1

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0    48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...  44.0  7800.0   
1     7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...  38.0  6000.0   
2    62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...  31.0  7500.0   
3    48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...  32.0  6700.0   
4    51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...  35.0  7300.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...  ...   ...     ...   
395  55.0  80.0  1.020  0.0  0.0    0   0    0   0  140.0  ...  47.0  6700.0   
396  42.0  70.0  1.025  0.0  0.0    0   0    0   0   75.0  ...  54.0  7800.0   
397  12.0  80.0  1.020  0.0  0.0    0   0    0   0  100.0  ...  49.0  6600.0   
398  17.0  60.0  1.025  0.0  0.0    0   0    0   0  114.0  ...  51.0  7200.0   
399  58.0  80.0  1.025  0.0  0.0    0   0    0   0  131.0  ...  53.0  6800.0   

      rc  htn  dm  cad  appet  pe  ane  classification  
0    5.2    1   1    0      0   0    0               0  
1    5.2    0   0    0      0   0    0               0  
2    5.2    0   1    0      1   0    1               0  
3    3.9    1   0    0      1   1    1               0  
4    4.6    0   0    0      0   0    0               0  
..   ...  ...  ..  ...    ...  ..  ...             ...  
395  4.9    0   0    0      0   0    0               1  
396  6.2    0   0    0      0   0    0               1  
397  5.4    0   0    0      0   0    0               1  
398  5.9    0   0    0      0   0    0               1  
399  6.1    0   0    0      0   0    0               1  

[400 rows x 25 columns]

In [35]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data1['pc']=l.fit_transform(data1['pc'])
data1

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0    48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...  44.0  7800.0   
1     7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...  38.0  6000.0   
2    62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...  31.0  7500.0   
3    48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...  32.0  6700.0   
4    51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...  35.0  7300.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...  ...   ...     ...   
395  55.0  80.0  1.020  0.0  0.0    0   0    0   0  140.0  ...  47.0  6700.0   
396  42.0  70.0  1.025  0.0  0.0    0   0    0   0   75.0  ...  54.0  7800.0   
397  12.0  80.0  1.020  0.0  0.0    0   0    0   0  100.0  ...  49.0  6600.0   
398  17.0  60.0  1.025  0.0  0.0    0   0    0   0  114.0  ...  51.0  7200.0   
399  58.0  80.0  1.025  0.0  0.0    0   0    0   0  131.0  ...  53.0  6800.0   

      rc  htn  dm  cad  appet  pe  ane  classification  
0    5.2    1   1    0      0   0    0               0  
1    5.2    0   0    0      0   0    0               0  
2    5.2    0   1    0      1   0    1               0  
3    3.9    1   0    0      1   1    1               0  
4    4.6    0   0    0      0   0    0               0  
..   ...  ...  ..  ...    ...  ..  ...             ...  
395  4.9    0   0    0      0   0    0               1  
396  6.2    0   0    0      0   0    0               1  
397  5.4    0   0    0      0   0    0               1  
398  5.9    0   0    0      0   0    0               1  
399  6.1    0   0    0      0   0    0               1  

[400 rows x 25 columns]

In [36]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data1['dm']=l.fit_transform(data1['dm'])
data1

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0    48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...  44.0  7800.0   
1     7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...  38.0  6000.0   
2    62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...  31.0  7500.0   
3    48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...  32.0  6700.0   
4    51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...  35.0  7300.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...  ...   ...     ...   
395  55.0  80.0  1.020  0.0  0.0    0   0    0   0  140.0  ...  47.0  6700.0   
396  42.0  70.0  1.025  0.0  0.0    0   0    0   0   75.0  ...  54.0  7800.0   
397  12.0  80.0  1.020  0.0  0.0    0   0    0   0  100.0  ...  49.0  6600.0   
398  17.0  60.0  1.025  0.0  0.0    0   0    0   0  114.0  ...  51.0  7200.0   
399  58.0  80.0  1.025  0.0  0.0    0   0    0   0  131.0  ...  53.0  6800.0   

      rc  htn  dm  cad  appet  pe  ane  classification  
0    5.2    1   1    0      0   0    0               0  
1    5.2    0   0    0      0   0    0               0  
2    5.2    0   1    0      1   0    1               0  
3    3.9    1   0    0      1   1    1               0  
4    4.6    0   0    0      0   0    0               0  
..   ...  ...  ..  ...    ...  ..  ...             ...  
395  4.9    0   0    0      0   0    0               1  
396  6.2    0   0    0      0   0    0               1  
397  5.4    0   0    0      0   0    0               1  
398  5.9    0   0    0      0   0    0               1  
399  6.1    0   0    0      0   0    0               1  

[400 rows x 25 columns]

In [37]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data1['appet']=l.fit_transform(data1['appet'])
data1

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0    48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...  44.0  7800.0   
1     7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...  38.0  6000.0   
2    62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...  31.0  7500.0   
3    48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...  32.0  6700.0   
4    51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...  35.0  7300.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...  ...   ...     ...   
395  55.0  80.0  1.020  0.0  0.0    0   0    0   0  140.0  ...  47.0  6700.0   
396  42.0  70.0  1.025  0.0  0.0    0   0    0   0   75.0  ...  54.0  7800.0   
397  12.0  80.0  1.020  0.0  0.0    0   0    0   0  100.0  ...  49.0  6600.0   
398  17.0  60.0  1.025  0.0  0.0    0   0    0   0  114.0  ...  51.0  7200.0   
399  58.0  80.0  1.025  0.0  0.0    0   0    0   0  131.0  ...  53.0  6800.0   

      rc  htn  dm  cad  appet  pe  ane  classification  
0    5.2    1   1    0      0   0    0               0  
1    5.2    0   0    0      0   0    0               0  
2    5.2    0   1    0      1   0    1               0  
3    3.9    1   0    0      1   1    1               0  
4    4.6    0   0    0      0   0    0               0  
..   ...  ...  ..  ...    ...  ..  ...             ...  
395  4.9    0   0    0      0   0    0               1  
396  6.2    0   0    0      0   0    0               1  
397  5.4    0   0    0      0   0    0               1  
398  5.9    0   0    0      0   0    0               1  
399  6.1    0   0    0      0   0    0               1  

[400 rows x 25 columns]

In [38]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data1['ane']=l.fit_transform(data1['ane'])
data1

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0    48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...  44.0  7800.0   
1     7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...  38.0  6000.0   
2    62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...  31.0  7500.0   
3    48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...  32.0  6700.0   
4    51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...  35.0  7300.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...  ...   ...     ...   
395  55.0  80.0  1.020  0.0  0.0    0   0    0   0  140.0  ...  47.0  6700.0   
396  42.0  70.0  1.025  0.0  0.0    0   0    0   0   75.0  ...  54.0  7800.0   
397  12.0  80.0  1.020  0.0  0.0    0   0    0   0  100.0  ...  49.0  6600.0   
398  17.0  60.0  1.025  0.0  0.0    0   0    0   0  114.0  ...  51.0  7200.0   
399  58.0  80.0  1.025  0.0  0.0    0   0    0   0  131.0  ...  53.0  6800.0   

      rc  htn  dm  cad  appet  pe  ane  classification  
0    5.2    1   1    0      0   0    0               0  
1    5.2    0   0    0      0   0    0               0  
2    5.2    0   1    0      1   0    1               0  
3    3.9    1   0    0      1   1    1               0  
4    4.6    0   0    0      0   0    0               0  
..   ...  ...  ..  ...    ...  ..  ...             ...  
395  4.9    0   0    0      0   0    0               1  
396  6.2    0   0    0      0   0    0               1  
397  5.4    0   0    0      0   0    0               1  
398  5.9    0   0    0      0   0    0               1  
399  6.1    0   0    0      0   0    0               1  

[400 rows x 25 columns]

In [39]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data1['classification']=l.fit_transform(data1['classification'])
data1

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0    48.0  80.0  1.020  1.0  0.0    0   0    0   0  121.0  ...  44.0  7800.0   
1     7.0  50.0  1.020  4.0  0.0    0   0    0   0    NaN  ...  38.0  6000.0   
2    62.0  80.0  1.010  2.0  3.0    0   0    0   0  423.0  ...  31.0  7500.0   
3    48.0  70.0  1.005  4.0  0.0    0   1    1   0  117.0  ...  32.0  6700.0   
4    51.0  80.0  1.010  2.0  0.0    0   0    0   0  106.0  ...  35.0  7300.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...  ...   ...     ...   
395  55.0  80.0  1.020  0.0  0.0    0   0    0   0  140.0  ...  47.0  6700.0   
396  42.0  70.0  1.025  0.0  0.0    0   0    0   0   75.0  ...  54.0  7800.0   
397  12.0  80.0  1.020  0.0  0.0    0   0    0   0  100.0  ...  49.0  6600.0   
398  17.0  60.0  1.025  0.0  0.0    0   0    0   0  114.0  ...  51.0  7200.0   
399  58.0  80.0  1.025  0.0  0.0    0   0    0   0  131.0  ...  53.0  6800.0   

      rc  htn  dm  cad  appet  pe  ane  classification  
0    5.2    1   1    0      0   0    0               0  
1    5.2    0   0    0      0   0    0               0  
2    5.2    0   1    0      1   0    1               0  
3    3.9    1   0    0      1   1    1               0  
4    4.6    0   0    0      0   0    0               0  
..   ...  ...  ..  ...    ...  ..  ...             ...  
395  4.9    0   0    0      0   0    0               1  
396  6.2    0   0    0      0   0    0               1  
397  5.4    0   0    0      0   0    0               1  
398  5.9    0   0    0      0   0    0               1  
399  6.1    0   0    0      0   0    0               1  

[400 rows x 25 columns]

In [40]:
data1.isnull().any()

age                True
bp                 True
sg                 True
al                 True
su                 True
rbc               False
pc                False
pcc               False
ba                False
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [41]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [42]:
imputer.fit(features[:,[0,1,2,3,4,9,10,11,12,13,14,15]])
features[:,[0,1,2,3,4,9,10,11,12,13,14,15]]=imputer.fit_transform(features[:,[0,1,2,3,4,9,10,11,12,13,14,15]])


In [43]:
new_data=pd.DataFrame(features)
new_data.isnull().any()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [44]:
x=data1.iloc[:,1:24]

In [45]:
x

bp     sg   al   su  rbc  pc  pcc  ba    bgr    bu  ...  hemo   pcv  \
0    80.0  1.020  1.0  0.0    0   0    0   0  121.0  36.0  ...  15.4  44.0   
1    50.0  1.020  4.0  0.0    0   0    0   0    NaN  18.0  ...  11.3  38.0   
2    80.0  1.010  2.0  3.0    0   0    0   0  423.0  53.0  ...   9.6  31.0   
3    70.0  1.005  4.0  0.0    0   1    1   0  117.0  56.0  ...  11.2  32.0   
4    80.0  1.010  2.0  0.0    0   0    0   0  106.0  26.0  ...  11.6  35.0   
..    ...    ...  ...  ...  ...  ..  ...  ..    ...   ...  ...   ...   ...   
395  80.0  1.020  0.0  0.0    0   0    0   0  140.0  49.0  ...  15.7  47.0   
396  70.0  1.025  0.0  0.0    0   0    0   0   75.0  31.0  ...  16.5  54.0   
397  80.0  1.020  0.0  0.0    0   0    0   0  100.0  26.0  ...  15.8  49.0   
398  60.0  1.025  0.0  0.0    0   0    0   0  114.0  50.0  ...  14.2  51.0   
399  80.0  1.025  0.0  0.0    0   0    0   0  131.0  18.0  ...  15.8  53.0   

         wc   rc  htn  dm  cad  appet  pe  ane  
0    7800.0  5.2    1   1    0      0   0    0  
1    6000.0  5.2    0   0    0      0   0    0  
2    7500.0  5.2    0   1    0      1   0    1  
3    6700.0  3.9    1   0    0      1   1    1  
4    7300.0  4.6    0   0    0      0   0    0  
..      ...  ...  ...  ..  ...    ...  ..  ...  
395  6700.0  4.9    0   0    0      0   0    0  
396  7800.0  6.2    0   0    0      0   0    0  
397  6600.0  5.4    0   0    0      0   0    0  
398  7200.0  5.9    0   0    0      0   0    0  
399  6800.0  6.1    0   0    0      0   0    0  

[400 rows x 23 columns]

In [46]:
y=data1.iloc[:,24].values

In [47]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [48]:
data1.isnull()

age     bp     sg     al     su    rbc     pc    pcc     ba    bgr  \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False   True   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
395  False  False  False  False  False  False  False  False  False  False   
396  False  False  False  False  False  False  False  False  False  False   
397  False  False  False  False  False  False  False  False  False  False   
398  False  False  False  False  False  False  False  False  False  False   
399  False  False  False  False  False  False  False  False  False  False   

     ...    pcv     wc     rc    htn     dm    cad  appet     pe    ane  \
0    ...  False  False  False  False  False  False  False  False  False   
1    ...  False  False  False  False  False  False  False  False  False   
2    ...  False  False  False  False  False  False  False  False  False   
3    ...  False  False  False  False  False  False  False  False  False   
4    ...  False  False  False  False  False  False  False  False  False   
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
395  ...  False  False  False  False  False  False  False  False  False   
396  ...  False  False  False  False  False  False  False  False  False   
397  ...  False  False  False  False  False  False  False  False  False   
398  ...  False  False  False  False  False  False  False  False  False   
399  ...  False  False  False  False  False  False  False  False  False   

     classification  
0             False  
1             False  
2             False  
3             False  
4             False  
..              ...  
395           False  
396           False  
397           False  
398           False  
399           False  

[400 rows x 25 columns]

In [49]:
new_data.columns = ('age','bp','sg','al','su','rbc','pc','pcc','ba','bgr','bu','se','sod','pot','hemo','pcv','wc','rc','htn','dm','cad','appet','pe','ane','classification')
new_data.head()

age    bp     sg   al   su  rbc   pc  pcc   ba         bgr  ...   pcv  \
0  48.0  80.0  1.020  1.0  0.0  0.0  0.0  0.0  0.0  121.000000  ...  44.0   
1   7.0  50.0  1.020  4.0  0.0  0.0  0.0  0.0  0.0  148.036517  ...  38.0   
2  62.0  80.0  1.010  2.0  3.0  0.0  0.0  0.0  0.0  423.000000  ...  31.0   
3  48.0  70.0  1.005  4.0  0.0  0.0  1.0  1.0  0.0  117.000000  ...  32.0   
4  51.0  80.0  1.010  2.0  0.0  0.0  0.0  0.0  0.0  106.000000  ...  35.0   

       wc   rc  htn   dm  cad  appet   pe  ane  classification  
0  7800.0  5.2  1.0  1.0  0.0    0.0  0.0  0.0             0.0  
1  6000.0  5.2  0.0  0.0  0.0    0.0  0.0  0.0             0.0  
2  7500.0  5.2  0.0  1.0  0.0    1.0  0.0  1.0             0.0  
3  6700.0  3.9  1.0  0.0  0.0    1.0  1.0  1.0             0.0  
4  7300.0  4.6  0.0  0.0  0.0    0.0  0.0  0.0             0.0  

[5 rows x 25 columns]

In [50]:
new_data.shape

(400, 25)

In [51]:
new_data.corr()

age        bp        sg        al        su       rbc  \
age             1.000000  0.148004 -0.180570  0.114764  0.207857  0.011783   
bp              0.148004  1.000000 -0.182463  0.146593  0.200784  0.151369   
sg             -0.180570 -0.182463  1.000000 -0.466698 -0.287993 -0.236228   
al              0.114764  0.146593 -0.466698  1.000000  0.268070  0.373927   
su              0.207857  0.200784 -0.287993  0.268070  1.000000  0.074324   
rbc             0.011783  0.151369 -0.236228  0.373927  0.074324  1.000000   
pc              0.101951  0.156856 -0.345325  0.535157  0.168826  0.377394   
pcc             0.159074  0.059560 -0.290663  0.399749  0.151445  0.102948   
ba              0.043573  0.112173 -0.220792  0.367855  0.107684  0.184402   
bgr             0.214410  0.149100 -0.326339  0.326400  0.639186  0.153076   
bu              0.187544  0.183970 -0.278568  0.405778  0.152186  0.236322   
se              0.127316  0.144359 -0.213513  0.230479  0.130122  0.138394   
sod            -0.085949 -0.103220  0.242841 -0.271316 -0.073715 -0.140572   
pot             0.050148  0.066648 -0.061821  0.114427  0.181015 -0.018192   
hemo           -0.175380 -0.279535  0.531755 -0.549697 -0.191518 -0.280990   
pcv            -0.167598 -0.223762  0.392311 -0.408185 -0.154185 -0.232256   
wc              0.116554  0.039957 -0.243869  0.223967  0.165610  0.021104   
rc             -0.203129 -0.209598  0.383420 -0.393725 -0.157249 -0.166161   
htn             0.393440  0.270447 -0.366959  0.481724  0.293179  0.140538   
dm              0.363475  0.228250 -0.393190  0.378042  0.472330  0.145646   
cad             0.232951  0.086618 -0.154803  0.236745  0.246702  0.111493   
appet           0.157741  0.177601 -0.246822  0.330562  0.080648  0.160868   
pe              0.094434  0.054083 -0.272476  0.440893  0.130721  0.199285   
ane             0.050567  0.194962 -0.213276  0.282305  0.066348  0.107625   
classification -0.225405 -0.290600  0.698957 -0.599238 -0.327812 -0.282642   

                      pc       pcc        ba       bgr  ...       pcv  \
age             0.101951  0.159074  0.043573  0.214410  ... -0.167598   
bp              0.156856  0.059560  0.112173  0.149100  ... -0.223762   
sg             -0.345325 -0.290663 -0.220792 -0.326339  ...  0.392311   
al              0.535157  0.399749  0.367855  0.326400  ... -0.408185   
su              0.168826  0.151445  0.107684  0.639186  ... -0.154185   
rbc             0.377394  0.102948  0.184402  0.153076  ... -0.232256   
pc              1.000000  0.520118  0.330401  0.262259  ... -0.360741   
pcc             0.520118  1.000000  0.275082  0.197593  ... -0.278041   
ba              0.330401  0.275082  1.000000  0.085940  ... -0.160221   
bgr             0.262259  0.197593  0.085940  1.000000  ... -0.193700   
bu              0.344048  0.184415  0.158444  0.127489  ... -0.417129   
se              0.157896  0.049940  0.050830  0.082242  ... -0.248241   
sod            -0.173323 -0.142135 -0.081733 -0.154393  ...  0.279224   
pot             0.158750 -0.006316 -0.002688  0.056695  ... -0.071654   
hemo           -0.411500 -0.275763 -0.204954 -0.269149  ...  0.658212   
pcv            -0.360741 -0.278041 -0.160221 -0.193700  ...  1.000000   
wc              0.107753  0.158224  0.095702  0.137186  ... -0.095653   
rc             -0.365479 -0.238772 -0.186593 -0.194327  ...  0.616166   
htn             0.291719  0.195623  0.089046  0.369849  ... -0.466613   
dm              0.201032  0.165236  0.080070  0.500618  ... -0.346144   
cad             0.172295  0.188029  0.162395  0.212433  ... -0.275903   
appet           0.274985  0.189688  0.149126  0.176132  ... -0.252915   
pe              0.350227  0.104356  0.134732  0.101502  ... -0.279413   
ane             0.260566  0.175861  0.052208  0.126854  ... -0.444377   
classification -0.375154 -0.265313 -0.186871 -0.401374  ...  0.427353   

                      wc        rc       htn        dm       cad     appet  \
age            

In [52]:
x

bp     sg   al   su  rbc  pc  pcc  ba    bgr    bu  ...  hemo   pcv  \
0    80.0  1.020  1.0  0.0    0   0    0   0  121.0  36.0  ...  15.4  44.0   
1    50.0  1.020  4.0  0.0    0   0    0   0    NaN  18.0  ...  11.3  38.0   
2    80.0  1.010  2.0  3.0    0   0    0   0  423.0  53.0  ...   9.6  31.0   
3    70.0  1.005  4.0  0.0    0   1    1   0  117.0  56.0  ...  11.2  32.0   
4    80.0  1.010  2.0  0.0    0   0    0   0  106.0  26.0  ...  11.6  35.0   
..    ...    ...  ...  ...  ...  ..  ...  ..    ...   ...  ...   ...   ...   
395  80.0  1.020  0.0  0.0    0   0    0   0  140.0  49.0  ...  15.7  47.0   
396  70.0  1.025  0.0  0.0    0   0    0   0   75.0  31.0  ...  16.5  54.0   
397  80.0  1.020  0.0  0.0    0   0    0   0  100.0  26.0  ...  15.8  49.0   
398  60.0  1.025  0.0  0.0    0   0    0   0  114.0  50.0  ...  14.2  51.0   
399  80.0  1.025  0.0  0.0    0   0    0   0  131.0  18.0  ...  15.8  53.0   

         wc   rc  htn  dm  cad  appet  pe  ane  
0    7800.0  5.2    1   1    0      0   0    0  
1    6000.0  5.2    0   0    0      0   0    0  
2    7500.0  5.2    0   1    0      1   0    1  
3    6700.0  3.9    1   0    0      1   1    1  
4    7300.0  4.6    0   0    0      0   0    0  
..      ...  ...  ...  ..  ...    ...  ..  ...  
395  6700.0  4.9    0   0    0      0   0    0  
396  7800.0  6.2    0   0    0      0   0    0  
397  6600.0  5.4    0   0    0      0   0    0  
398  7200.0  5.9    0   0    0      0   0    0  
399  6800.0  6.1    0   0    0      0   0    0  

[400 rows x 23 columns]

In [53]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

# To convert series values to Array Format for Onehot Encoding

In [54]:
x=new_data.iloc[:,0:24].values
y=new_data.iloc[:,24].values
type(x)

numpy.ndarray

In [55]:
x.shape

(400, 24)

In [56]:
y.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

# Feature Scaling

In [62]:
from sklearn import preprocessing
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.52272727, 0.23076923, 0.75      , ..., 0.        , 0.        ,
        0.        ],
       [0.05681818, 0.        , 0.75      , ..., 0.        , 0.        ,
        0.        ],
       [0.68181818, 0.23076923, 0.25      , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.11363636, 0.23076923, 0.75      , ..., 0.        , 0.        ,
        0.        ],
       [0.17045455, 0.07692308, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.63636364, 0.23076923, 1.        , ..., 0.        , 0.        ,
        0.        ]])

# Splitting the data into train

In [63]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size  = 0.2)

In [64]:
x_train

array([[ 42.   ,  70.   ,   1.02 , ...,   0.   ,   0.   ,   0.   ],
       [ 34.   ,  70.   ,   1.025, ...,   0.   ,   0.   ,   0.   ],
       [ 55.   ,  80.   ,   1.01 , ...,   0.   ,   0.   ,   0.   ],
       ...,
       [ 41.   ,  70.   ,   1.015, ...,   0.   ,   1.   ,   1.   ],
       [ 66.   ,  70.   ,   1.02 , ...,   0.   ,   0.   ,   0.   ],
       [ 48.   , 110.   ,   1.015, ...,   0.   ,   0.   ,   1.   ]])

In [65]:
x_test

array([[90.   , 90.   ,  1.025, ...,  0.   ,  0.   ,  0.   ],
       [32.   , 90.   ,  1.025, ...,  1.   ,  1.   ,  1.   ],
       [55.   , 80.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       ...,
       [71.   , 60.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [38.   , 60.   ,  1.02 , ...,  0.   ,  0.   ,  0.   ],
       [70.   , 90.   ,  1.015, ...,  1.   ,  1.   ,  0.   ]])

In [66]:
y_train

array([1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 0.

In [67]:
y_test

array([0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
       0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0.])

In [68]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform (x_test)

In [69]:
x_train

array([[-0.53197288, -0.49915785,  0.49251234, ..., -0.51460872,
        -0.4853053 , -0.42008403],
       [-0.99355712, -0.49915785,  1.41820608, ..., -0.51460872,
        -0.4853053 , -0.42008403],
       [ 0.2181015 ,  0.2409446 , -1.35887514, ..., -0.51460872,
        -0.4853053 , -0.42008403],
       ...,
       [-0.58967091, -0.49915785, -0.4331814 , ..., -0.51460872,
         2.06055857,  2.38047614],
       [ 0.85277983, -0.49915785,  0.49251234, ..., -0.51460872,
        -0.4853053 , -0.42008403],
       [-0.1857847 ,  2.46125195, -0.4331814 , ..., -0.51460872,
        -0.4853053 ,  2.38047614]])

In [70]:
x_test

array([[ 2.23753253,  0.98104705,  1.41820608, ..., -0.51460872,
        -0.4853053 , -0.42008403],
       [-1.10895318,  0.98104705,  1.41820608, ...,  1.94322397,
         2.06055857,  2.38047614],
       [ 0.2181015 ,  0.2409446 ,  0.49251234, ..., -0.51460872,
        -0.4853053 , -0.42008403],
       ...,
       [ 1.14126997, -1.2392603 ,  0.49251234, ..., -0.51460872,
        -0.4853053 , -0.42008403],
       [-0.762765  , -1.2392603 ,  0.49251234, ..., -0.51460872,
        -0.4853053 , -0.42008403],
       [ 1.08357194,  0.98104705, -0.4331814 , ...,  1.94322397,
         2.06055857, -0.42008403]])

In [71]:
y_train

array([1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 0.

In [72]:
y_test

array([0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
       0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0.])

In [73]:
x_test.shape

(80, 24)

In [74]:
y_test.shape

(80,)